apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment  # He asignado un nombre único al deployment
spec:
  replicas: 3                   # Puedes ajustar el número de réplicas según tus necesidades (en este ejemplo, 3)
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        image: carlosguamantica/backend-flask:1.0.0  # He reemplazado el placeholder con mi usuario y nombre de imagen
        ports:
        - containerPort: 5001
