apiVersion: apps/v1
kind: Deployment
metadata:
  name:  # TODO: Add a unique name 
spec:
  replicas:   # TODO: Adjust the replica count as desired
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        # TODO: Replace <your-dockerhub-username> with your Docker Hub username
        image: <your-dockerhub-username>/<backend-image-name>:1.0.0
        ports:
        - containerPort: 5001
